apiVersion: v2
name: ixo-matrix-whatsapp
description: Helm chart for mautrix-whatsapp (Matrix-WhatsApp bridge) on Kubernetes
type: application
version: 0.1.1
appVersion: "v26.07"
keywords:
  - matrix
  - whatsapp
  - bridge
  - mautrix
maintainers: []
dependencies: []
