apiVersion: v2
name: memory-engine-graphiti
description: A Helm chart for Kubernetes
type: application
version: 0.0.18
appVersion: main-ee6f7c2
dependencies:
- name: matrix-bridge-api
  version: 0.0.3
  repository: file://./charts/matrix-bridge-api
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update ixoworld/memory-engine-graphiti app version from main-8bad766 to main-ee6f7c2
