{{- if .Values.secretFiles }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sygnal.fullname" . }}-files
  labels:
    {{- include "sygnal.labels" . | nindent 4 }}
data:
  {{- range $filename, $value := .Values.secretFiles }}
  {{ $filename }}: {{ $value }}
  {{- end }}
{{- end }}
