apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ixo-matrix-bids-bot.fullname" . }}-config
  labels:
    {{- include "ixo-matrix-bids-bot.labels" . | nindent 4 }}
{{- $cfg := .Values.config | default dict }}
{{- $ucan := $cfg.ucan | default dict }}
{{- $restApi := $cfg.restApi | default dict }}
data:
  production.yaml: |-
    # Where the homeserver's Client-Server API is located. Typically this
    # is where clients would be connecting to in order to send messages.
    homeserverUrl: {{ $cfg.homeserverUrl | default "http://matrix-synapse.matrix-synapse.svc.cluster.local:8008" | quote }}
    homeserverName: {{ $cfg.homeserverName | default "mx.ixo.earth" | quote }}
    accessToken: {{ $cfg.accessToken | default "<path:ixo_core/data/matrix#MATRIX_BIDS_BOT_ACCESS_TOKEN>" }}
    graphqlUrl: {{ $cfg.graphqlUrl | default "https://blocksync-graphql.ixo.earth/graphql" | quote }}
    rpcUrl: {{ $cfg.rpcUrl | default "https://impactHub.ixo.world/rpc/" | quote }}

    # Whether or not to autojoin rooms when invited.
    autoJoin: {{ if (hasKey $cfg "autoJoin") }}{{ $cfg.autoJoin }}{{ else }}true{{ end }}

    # Location on disk for where to store various bot information.
    dataPath: {{ $cfg.dataPath | default "./ixo-bids-bot-storage" | quote }}

    encryption: {{ if (hasKey $cfg "encryption") }}{{ $cfg.encryption }}{{ else }}true{{ end }}

    # Recovery key for restoring encryption keys from server backup
    # Format: Base58 with spaces (e.g., "EsTc LW2K ...")
    recoveryKey: {{ $cfg.recoveryKey | default "<path:ixo_core/data/matrix#MATRIX_BID_BOT_RECOVERY_KEY>" }}

    # The blockchain API endpoint to query for DID documents
    blockchainRpcUri: {{ $cfg.blockchainRpcUri | default "https://impactHub.ixo.world/rpc/" | quote }}

    # The blocksync API endpoint to query for users DID documents using graphql
    blocksyncUri: {{ $cfg.blocksyncUri | default "https://blocksync-graphql.ixo.earth/" | quote }}

    # Network (devnet or testnet or mainnet)
    network: {{ $cfg.network | default "mainnet" | quote }}

    # REST API config
    ucan:
      mnemonic: {{ $ucan.mnemonic | default "<path:ixo_core/data/matrix#MATRIX_BIDS_BOT_DID_MNEMONIC>" }}
      hostname: {{ $ucan.hostname | default "bid.bot.mx.ixo.earth" | quote }}

    restApi:
      # Set to true to enable the REST API
      enabled: {{ if (hasKey $restApi "enabled") }}{{ $restApi.enabled }}{{ else }}true{{ end }}
      # Port to listen on for the REST API, default is 8080
      port: {{ $restApi.port | default 8083 }}
      # express trust proxy config for if you are using a reverse proxy
      trustProxy: {{ $restApi.trustProxy | default 1 }}
