apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ixo-matrix-whatsapp.fullname" . }}-registration
  labels:
    {{- include "ixo-matrix-whatsapp.labels" . | nindent 4 }}
data:
  registration.yaml: |-
    id: whatsapp
    as_token: {{ .Values.appservice.as_token | quote }}
    hs_token: {{ .Values.appservice.hs_token | quote }}
    sender_localpart: whatsappbot
    url: {{ .Values.appservice.address | quote }}
    namespaces:
      users:
        - exclusive: true
          regex: "@wa_.*:{{ .Values.homeserver.domain }}"
      aliases: []
      rooms: []
    rate_limited: false
    de.sorunome.msc2409.push_ephemeral: true
    org.matrix.msc3202: true
