apiVersion: v2
name: memory-engine-graphiti
description: A Helm chart for Kubernetes
type: application
version: 0.0.13
appVersion: "main-44fd24d"
dependencies:
- name: matrix-bridge-api
  version: 0.0.4
  repository: file://./charts/matrix-bridge-api
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update ixoworld/memory-engine-graphiti app version from v1.2.1 to main-44fd24d
