apiVersion: v2
name: memory-engine-graphiti
description: A Helm chart for Kubernetes
type: application
version: 0.0.21
appVersion: "main-4460b43"
dependencies:
  - name: matrix-bridge-api
    version: 0.0.6
    repository: file://./charts/matrix-bridge-api
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update ixoworld/memory-engine-graphiti app version from main-285dca2 to main-c9c4ade
