apiVersion: v2
name: domain-indexer
description: A Helm chart for Kubernetes
type: application
version: 0.0.19
appVersion: v1.16.0
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update ixoworld/domain-indexer app version from v1.15.0 to v1.16.0
