apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "memory-engine-graphiti.memoryEngineFullname" . }}-storage
  labels:
    {{- include "memory-engine-graphiti.labels" . | nindent 4 }}
    app.kubernetes.io/component: memory-engine
spec:
  accessModes:
    {{- .Values.persistentVolume.accessModes | toYaml | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.size }}
  storageClassName: {{ .Values.persistentVolume.storageClass }}
