apiVersion: v2
name: api-server
description: Firecrawler API Server component
type: application
version: 0.0.4
appVersion: main-58595ea
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Update api-server app version from main-70d62d8 to main-58595ea
